// Copies ABIs (and the PasskeyAccount bytecode) from the Foundry build output into src/abi/generated.ts.
// Run `forge build` in contracts/ first. Committed output keeps the published package self-contained.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../../contracts/out");

const artifacts = {
  MandateRegistry: "MandateRegistry.sol/MandateRegistry.json",
  MandateExecutor: "MandateExecutor.sol/MandateExecutor.json",
  RiskBreaker: "RiskBreaker.sol/RiskBreaker.json",
  PasskeyAccount: "PasskeyAccount.sol/PasskeyAccount.json",
  PrivateSubmitter: "PrivateSubmitter.sol/PrivateSubmitter.json",
  ERC8004ReputationAdapter: "ERC8004ReputationAdapter.sol/ERC8004ReputationAdapter.json",
  ERC8004ReputationRegistry: "IERC8004.sol/IERC8004ReputationRegistry.json",
  ERC8004IdentityRegistry: "IERC8004.sol/IERC8004IdentityRegistry.json",
};

let ts = `// AUTO-GENERATED by scripts/sync-abi.mjs from contracts/out. Do not edit.\n\n`;
for (const [name, rel] of Object.entries(artifacts)) {
  const art = JSON.parse(readFileSync(resolve(out, rel), "utf8"));
  ts += `export const ${name}Abi = ${JSON.stringify(art.abi, null, 2)} as const;\n\n`;
  if (name === "PasskeyAccount") {
    ts += `export const PasskeyAccountBytecode = ${JSON.stringify(art.bytecode.object)} as const;\n\n`;
  }
}
writeFileSync(resolve(here, "../src/abi/generated.ts"), ts);
console.log("wrote src/abi/generated.ts");
